-- Data for table: States
-- Row count: 51

IF NOT EXISTS (SELECT 1 FROM [States])
BEGIN
    INSERT INTO [States] ([StateAbbrev], [StateName])
    VALUES
        (N'AK', N'Alaska'),
        (N'AL', N'Alabama'),
        (N'AR', N'Arkansas'),
        (N'AZ', N'Arizona'),
        (N'CA', N'California'),
        (N'CO', N'Colorado'),
        (N'CT', N'Connecticut'),
        (N'DC', N'District of Columbia'),
        (N'DE', N'Delaware'),
        (N'FL', N'Florida'),
        (N'GA', N'Georgia'),
        (N'HI', N'Hawaii'),
        (N'IA', N'Iowa'),
        (N'ID', N'Idaho'),
        (N'IL', N'Illinois'),
        (N'IN', N'Indiana'),
        (N'KS', N'Kansas'),
        (N'KY', N'Kentucky'),
        (N'LA', N'Louisiana'),
        (N'MA', N'Massachusetts'),
        (N'MD', N'Maryland'),
        (N'ME', N'Maine'),
        (N'MI', N'Michigan'),
        (N'MN', N'Minnesota'),
        (N'MO', N'Missouri'),
        (N'MS', N'Mississippi'),
        (N'MT', N'Montana'),
        (N'NC', N'North Carolina'),
        (N'ND', N'North Dakota'),
        (N'NE', N'Nebraska'),
        (N'NH', N'New Hampshire'),
        (N'NJ', N'New Jersey'),
        (N'NM', N'New Mexico'),
        (N'NV', N'Nevada'),
        (N'NY', N'New York'),
        (N'OH', N'Ohio'),
        (N'OK', N'Oklahoma'),
        (N'OR', N'Oregon'),
        (N'PA', N'Pennsylvania'),
        (N'RI', N'Rhode Island'),
        (N'SC', N'South Carolina'),
        (N'SD', N'South Dakota'),
        (N'TN', N'Tennessee'),
        (N'TX', N'Texas'),
        (N'UT', N'Utah'),
        (N'VA', N'Virginia'),
        (N'VT', N'Vermont'),
        (N'WA', N'Washington'),
        (N'WI', N'Wisconsin'),
        (N'WV', N'West Virginia'),
        (N'WY', N'Wyoming');
END